export const myProjects=[
    {
        title:"MadAlgos Coderground",
        desc:"At MadAlgos, I've developed an advanced code editor tailored specifically for our users. The editor is packed with a plethora of features, starting from smooth question loading to providing insightful hints and executing code seamlessly. To enhance the compilation process, I've integrated Azure Functions for our language compilers, allowing for efficient code compilation through server calls. I believe in giving our users full control, which is why I offer customization options such as toggling between dark and light modes, adjusting font size and tab spacing, and selecting from various code editor themes. Additionally, I've implemented an auto code save feature to ensure that our users never lose their valuable work. In essence, my code editor at MadAlgos is a powerful tool designed to meet the diverse needs of developers, educators, and learners alike. It provides a smooth and intuitive coding experience, empowering users to focus on their tasks without any distractions.",
        banner: "https://firebasestorage.googleapis.com/v0/b/hrishikesh-ghosh-portfolio.appspot.com/o/project%20Screenshots%2FMAD%20Algos%20-%20Google%20Chrome%204_21_2024%2012_21_56%20PM.png?alt=media&token=c74df5b8-d339-4971-9f43-6dd355166903",
        url:"https://madalgos.in/ide/coderground"
    },
    {
        title:"MadAlgos Clubs & Events",
        desc:"I spearheaded the creation of MadAlgos Clubs & Events, contributing extensively to both the backend and frontend development. My role involved designing the architectural flow of user actions on the platform, ensuring seamless navigation and engagement. Additionally, I devised strategies for capturing user data, whether it be through club and event enrollments or lead generation. One of the notable features I implemented is a dynamic timer that adjusts according to the user's personalized timezone, providing real-time updates on enrollment deadlines. This personalized touch enhances the user experience and encourages timely participation. To enrich the learning experience, I seamlessly integrated the MadAlgos Code Editor and Zoom for hands-on coding sessions and knowledge sharing events. This integration facilitates interactive learning environments, allowing participants to engage directly with the material and instructors. Overall, MadAlgos Clubs & Events stands as a dynamic platform for fostering learning and collaboration, with a focus on user engagement and personalized experiences",
        banner: "https://firebasestorage.googleapis.com/v0/b/hrishikesh-ghosh-portfolio.appspot.com/o/project%20Screenshots%2FMAD%20Algos%20-%20Google%20Chrome%204_21_2024%2012_28_30%20PM.png?alt=media&token=995001d1-43de-4a11-98c4-24a115170b3a",
        url:"https://madalgos.in/clubs"
    },
    {
        title:"MadAlgos Home Page Redesign",
        desc:"I took the initiative to redesign the UI for our home page, focusing on enhancing user experience and incorporating modern UI trends. Using Figma, I meticulously crafted the new design, ensuring it was both visually appealing and user-friendly. To bring the design to life, I then coded the front end, paying close attention to detail to ensure robustness and interactivity. Leveraging trendy UI designs, I aimed to create a sleek and immersive experience for our users. One of the key decisions was to adopt a dark appearance, which not only adds a touch of elegance but also aligns with current design aesthetics. This choice enhances readability and makes elements pop, creating a visually striking homepage. Overall, the redesigned UI reflects our commitment to providing an engaging and seamless experience for our users, while staying at the forefront of design trends.",
        banner:"https://firebasestorage.googleapis.com/v0/b/hrishikesh-ghosh-portfolio.appspot.com/o/project%20Screenshots%2FMAD%20Algos%20-%20Google%20Chrome%204_21_2024%201_05_28%20PM.png?alt=media&token=75fabc0c-3b0b-40e0-b42d-9c82068e35cb",
        url:"https://madalgos.in/"
    },
    {
        title:"RootNik Labs",
        desc:"I had the opportunity to develop the front end for Rootnik Labs, a startup dedicated to teaching ethical hacking to students. For this project, I opted not to use any front end frameworks but instead relied on basic HTML and CSS to create a robust and highly interactive website. By eschewing frameworks, I aimed to demonstrate the power and versatility of fundamental web development technologies. Leveraging HTML and CSS, I crafted a user-friendly interface that effectively communicates Rootnik Labs' mission and offerings to its audience. Despite the simplicity of the tools used, I ensured that the website maintained a high level of interactivity. Through careful design and implementation, users can seamlessly navigate through the content, access resources, and engage with the platform's features. This project serves as a testament to the importance of foundational skills in web development and showcases the potential for creating compelling user experiences without relying on complex frameworks.",
        banner:"https://firebasestorage.googleapis.com/v0/b/hrishikesh-ghosh-portfolio.appspot.com/o/project%20Screenshots%2FMAD%20Algos%20-%20Google%20Chrome%204_21_2024%201_09_44%20PM.png?alt=media&token=a62cd9fd-b1ae-426f-87a9-cf2037aa82b9",
        url:"https://www.rootniklabs.com/"
    },
    {
        title:"Ciem Mentorship Platform",
        desc:"I had the privilege of developing a website showcasing my college's alumni band, specifically focusing on their contributions to the research and development sector. Leveraging the power of the React.js framework, I set out to create a website that would not only be robust but also leave users awestruck by its interactivity and seamless user experience. By harnessing the capabilities of React.js, I was able to build a dynamic and responsive website that captures the essence of the alumni band's achievements and innovations in the research and development field. Through engaging animations, intuitive navigation, and immersive visuals, users are drawn into a captivating journey through the band's story and its impact on the R&D sector. Additionally, I incorporated features that enable users to explore the band's projects, collaborations, and milestones in an interactive manner, fostering a deeper understanding and appreciation for their contributions. Overall, the website stands as a testament to the transformative potential of React.js in crafting compelling digital experiences that not only inform but also inspire and captivate users",
        banner:"https://firebasestorage.googleapis.com/v0/b/hrishikesh-ghosh-portfolio.appspot.com/o/project%20Screenshots%2FMAD%20Algos%20-%20Google%20Chrome%204_21_2024%201_17_37%20PM.png?alt=media&token=11cfe1f1-4842-485f-8a92-c1cfaa568413",
        url:"https://codechef-ciem-chapter.netlify.app/#/home"
    },
]